### ISSUE TITLE
Missing file with `devices` for gamepad support for tele operation.

### ISSUE THREAD

**Issue by dosssman** [vikashplus/vtils#2]
Hello @vikashplus !

Thanks again for open-sourcing this library along side your robohive simulator.
I am trying to adapt the ee_teleop.py tutorial script to support gamepad, but it seems that the `devices` expected to be in the `inputs` file cannot be found.

https://github.com/vikashplus/vtils/blob/2c2d3a755aeee62811cd2a3ef542e9d0b8bf9c4f/vtils/input/gamepad.py#L3

Any chance you could share that missing file so I can build on top of it to get tele operation with a gamepad running ?

Thanks a lot for your time.
Best regards.

**Comment by vikashplus** [comment]
Hi @dosssman 
Thanks for your interest. Apologies for the poor user experience. It has been a while since I used this functionality. 
I believe the missing dependencies are one of these two
 - https://pypi.org/project/inputs/ 
 - https://pypi.org/project/pynput/
 
Please send a PR if you manage to get things working. Thank you
